export {
  EXTENSIONS_DIR_RELPATH,
  type ExtensionsFs,
  type ExtensionsFsEntry,
  type ExtensionsWriteFs,
  createZenfsExtensionsFs,
  createZenfsExtensionsWriteFs,
} from './extensions-fs';
export {
  DEFAULT_NPM_REGISTRY,
  installExtensionFromNpm,
  localExtensionDirName,
  parseNpmPackageSpec,
  type InstallExtensionInput,
  type InstalledExtension,
  type NpmPackageSpec,
} from './install';
export { discoverExtensions, type LoadedExtensionModule } from './loader';
export { ExtensionRegistry, type SessionBridge } from './registry';
export type {
  AfterProviderResponseEvent,
  AfterProviderResponseHandler,
  BeforeAgentStartEvent,
  BeforeAgentStartEventResult,
  BeforeAgentStartHandler,
  BeforeProviderRequestEvent,
  BeforeProviderRequestHandler,
  Disposable,
  ExtensionAPI,
  ExtensionCapabilities,
  ExtensionCommandDefinition,
  ExtensionCommandInfo,
  ExtensionEvent,
  ExtensionEventHandler,
  ExtensionEventsHandler,
  ExtensionEventsView,
  ExtensionFactory,
  ExtensionInfo,
  ExtensionSessionView,
  ExtensionTool,
  ExtensionTypeBuilder,
  ExtensionVolumesView,
  GenericExtensionEventHandler,
  InputEvent,
  InputEventResult,
  InputEventSource,
  InputHandler,
  InputResultContinue,
  InputResultHandled,
  InputResultTransform,
  ProviderConfig,
  ProviderModelConfig,
  ProviderOAuthConfig,
  ProviderOAuthCredentials,
  ProviderOAuthLoginCallbacks,
  ProviderStreamSimple,
  SessionStartEvent,
  SessionStartHandler,
  ToolCallEvent,
  ToolCallEventResult,
  ToolCallHandler,
  ToolResultEvent,
  ToolResultEventResult,
  ToolResultHandler,
} from './types';
